# Documentation for ACL policy: https://aka.ms/gim/docs/policy/acl

name: Access control list
description: List of teams and their permission levels
resource: repository
where:
configuration:
  manageAccess:
  - member: xingjianwang
    role: Maintain
  - member: torosent
    role: Maintain
  - member: jennylaw
    role: Maintain
  - member: ahmels
    role: Maintain
  - member: sanmeht
    role: Maintain
  - team: adcontainerapps
    role: Maintain
  - team: k4appscore
    role: Write
