name: perf-test
on:
  workflow_dispatch: { }
  push:
    branches:
      - main


jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Setup test output
        run: |
          export TEST_OUTPUT_FILE_PREFIX=$GITHUB_WORKSPACE/test_perf_report
          echo "TEST_OUTPUT_FILE_PREFIX=$TEST_OUTPUT_FILE_PREFIX" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build and Run perf test app
        run: |
          make run-perfapp-container
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
      
      - name: Run perf test
        run: |
          make run-perf-test

      - name: Collect container logs
        if: always()
        run: |
          docker logs perfapp-container > ${{ env.TEST_OUTPUT_FILE_PREFIX }}_logs.txt 2>&1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test_perf_results
          path: ${{ env.TEST_OUTPUT_FILE_PREFIX }}_*.*

      - name: Add job test summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: test_perf_report_summary.xml
      
      - name: Add job test outputs
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./tests/perf/tests_summary.js')
            await script({core, glob})

      - name: Delete perf test app
        if: always()
        run: |
          make delete-perfapp-container