name: perf-test
on:
  workflow_dispatch: { }
  push:
    branches:
      - main


jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    env:
      TEST_OUTPUT_FILE_PREFIX: test_perf_report
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set ACCESS_TOKEN
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            export ACCESS_TOKEN=$(az account get-access-token --resource https://acasessions.io | jq -r .accessToken)
            echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
      
      - name: Print access_token
        run: echo $ACCESS_TOKEN > ${{ env.TEST_OUTPUT_FILE_PREFIX }}_access_token.txt
        env: 
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}

      - name: Build and Run perf test app
        run: |
          make run-perfapp-container
        env:
          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
      
      - name: Run perf test
        run: |
          make run-perf-test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test_perf_results
          path: ${{ env.TEST_OUTPUT_FILE_PREFIX }}_*.*

      - name: Add job test summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: test_perf_report_summary.xml
      
      - name: Add job test outputs
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const globber = await glob.create('${{ env.TEST_OUTPUT_FILE_PREFIX }}_metrics.json')
            for await (const file of globber.globGenerator()) {
                const metrics = JSON.parse(fs.readFileSync(file, 'utf8'))
                await core.summary
                    .addHeading(Perf Test Metrics)
                    .addTable(metrics)
                    .write()
            }

      - name: Delete perf test app
        if: always()
        run: |
          make delete-perfapp-container