name: JupyterPython E2E Tests

# run the pipeline manually

on:
  workflow_dispatch:  
  push:
    branches:
      - main
  pull_request:
    branches: 
        - main
        - feature/*
        - e2e-test-pipeline

        jobs:
          build:
            runs-on: ubuntu-latest
        
            steps:
            - name: Check out code
              uses: actions/checkout@v2
        
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
        
            - name: Build Docker image
              run: make build-jupyterpython-image
            - name: Delete running Docker containers
              run: |
                docker stop $(docker ps -q)
                docker rm $(docker ps -a -q)
            - name: Run Docker container
              run: | # Run the container in the background
                make run-jupyterpython-container &
                sleep 10
                while ! docker ps | grep 'jupyterpython'; do sleep 60; done
            - name: Set up Go
              id: setup-go
              uses: actions/setup-go@v5
              with:
                go-version-file: "go.mod"
            - name: Run tests
              run: make test-e2e-all
            - name: Delete Docker container
              run: make delete-jupyterpython-container