name: perf-test
on:
  workflow_dispatch:
    inputs:
      scenario_type:
        type: choice
        description: 'Scenario type'
        required: true
        options:
        - constant
        - ramping
      qps:
        description: 'QPS(only used for constant scenario)'
        required: true
        default: 1
      duration:
        description: 'Duration(only used for constant scenario)'
        required: true
        default: '10s'
      region:
        type: choice
        description: 'Region'
        required: true
        options:
        - northcentralusstage
        - northcentralus
        - eastus
        - westus2
        - northeurope
        - koreacentral
        - eastasia
      
  push:
    branches:
      - main


jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Setup test output
        run: |
          export TEST_OUTPUT_FILE_PREFIX=$GITHUB_WORKSPACE/test_perf_report
          echo "TEST_OUTPUT_FILE_PREFIX=$TEST_OUTPUT_FILE_PREFIX" >> $GITHUB_ENV

      - name: Set environment variables
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "QPS=${{ github.event.inputs.qps }}" >> $GITHUB_ENV
            echo "DURATION=${{ github.event.inputs.duration }}" >> $GITHUB_ENV
            echo "SCENARIO_TYPE=${{ github.event.inputs.scenario_type }}" >> $GITHUB_ENV
          else
            echo "SCENARIO_TYPE=ramping" >> $GITHUB_ENV
          fi
          echo "REGION=${{ github.event.inputs.region }}" >> $GITHUB_ENV
        env:
          QPS_DEFAULT: 1
          DURATION_DEFAULT: '10s'

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build and Run perf test app
        run: |
          make run-perfapp-container
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
      
      - name: Create Session Pool
        run: |
          make create-pool

      - name: Run perf test
        run: |
          make run-perf-test

      - name: Collect container logs
        if: always()
        run: |
          docker logs perfapp-container > ${{ env.TEST_OUTPUT_FILE_PREFIX }}_logs.txt 2>&1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test_perf_results
          path: ${{ env.TEST_OUTPUT_FILE_PREFIX }}_*.*

      - name: Add job test summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: test_perf_report_summary.xml
      
      - name: Add job test outputs
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./tests/perf/tests_summary.js')
            await script({core, glob})

      - name: Delete perf test app
        if: always()
        run: |
          make delete-perfapp-container